### ISSUE TITLE
Neutron parts showing through wall (only neutron parts atm)

### ISSUE THREAD

**Issue by Henri979** [SpitefulFox/Avaritia#108] opened 2016-11-19 12:16 UTC
![2016-11-19_13 07 12](https://cloud.githubusercontent.com/assets/23419620/20455311/529ac206-ae59-11e6-9b60-d43df92e55e9.png)

The image shows that the Ingot (which is in a barrel from Jabba (Version 1.2.2_1.7.10)) is visual glitching through the wall (if it is importent these are Immersiv engineering (Version 0.7.7) and Immersive Integration (Version 0.6.8))
I use Avaritia version 1.11, if something else I would like to help.

The bug (if it is one) it seems to do nothing no lag frame drop or else.
We are on a server.

And something special, how do I change the recepie of something in the mod, for e.g. how do I remove the Thaumcraft pearl (Primal or so its called) from the Catalyst recepie?

Thank you for helping,
Henri979

**Comment by SpitefulFox** [comment] 2016-11-19 20:15
Duplicate of #61 

You can use Minetweaker to remove the catalyst recipe and then submit a new one without the pearl.  Or just turn off Thaumcraft integration in the config.

**Closed by SpitefulFox** 2016-11-19 20:15 UTC
Labels: duplicate
